[package]
name = "js-randomness-predictor-rust"
include = ["Cargo.toml", "**/*"]
version = "0.1.0"
edition = "2024"

[dependencies]
z3 = "0.12.1"

[[bin]]
name = "js-randomness-predictor-rust"
path = "main.rs"
